apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-pat-external
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: gh-pat
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: github-action-runners/gh-pat
        property: github_token
